name: Add labels
on:
  issues:
    types: [opened, edited, reopened]
jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.issue.title, '[Plugin][FR]:') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            âœ¨ Enhancement
            ğŸ’ Obsidian Github Publisher
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.issue.title, '[MKDOCS][FR]:') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            âœ¨ Enhancement
            ğŸ“« Material Mkdocs Template
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.issue.title, '[Plugin][Bug]:') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            ğŸ› Bug
            ğŸ’ Obsidian Github Publisher
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.issue.title, '[MKDOCS][Bug]:') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            ğŸ› Bug
            ğŸ“« Material Mkdocs Template
      
